services:
  web:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: api_tiago
    env_file:
      - .env
    ports:
      - "5000:5000"
    depends_on:
      - tiago_db
    environment:
      - FLASK_ENV=production
      - FLASK_SECRET_KEY=${FLASK_SECRET_KEY}
      - FLASK_DEBUG=${FLASK_DEBUG}
      - FLASK_SQLALCHEMY_DATABASE_URI=${FLASK_SQLALCHEMY_DATABASE_URI}
      - FLASK_SQLALCHEMY_ECHO=${FLASK_SQLALCHEMY_ECHO}
      - GEMINI_API_KEY=${GEMINI_API_KEY}
      - TELEGRAM_TOKEN=${TELEGRAM_TOKEN}
    command: python app.py

  tiago_db:
    image: postgres:16
    container_name: tiago_db
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"

volumes:
  postgres_data:
