services:
  web:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: api_tiago
    env_file:
      - .env
    ports:
      - "5000:5000"
    depends_on:
      - tiago_db
    environment:
      - FLASK_ENV=production
      - FLASK_SECRET_KEY=${FLASK_SECRET_KEY}
      - FLASK_DEBUG=${FLASK_DEBUG}
      - FLASK_SQLALCHEMY_DATABASE_URI=${FLASK_SQLALCHEMY_DATABASE_URI}
      - FLASK_SQLALCHEMY_ECHO=${FLASK_SQLALCHEMY_ECHO}
      - GEMINI_API_KEY=${GEMINI_API_KEY}
      - TELEGRAM_TOKEN=${TELEGRAM_TOKEN}
      - GOOGLE_APPLICATION_CREDENTIALS=/app/gen-lang-client-0549477230-23a4e460f7bf.json
      - VERTEX_AI_PROJECT_ID=gen-lang-client-0549477230
      - VERTEX_AI_LOCATION=southamerica-east1
    command: python app.py
    volumes:
      - ./src/uploads:/app/src/uploads  # Volume para persistir os arquivos de upload
      - ./src/path/gen-lang-client-0549477230-23a4e460f7bf.json:/app/gen-lang-client-0549477230-23a4e460f7bf.json

  tiago_db:
    image: postgres:16
    container_name: tiago_db
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - "5433:5433"  # Corrigido para evitar conflito com a porta padrão do PostgreSQL

volumes:
  postgres_data:
